import type { Product, Category } from '@/types'

// ═══════════════════════════════════════════
// PRODUCTOS REALES DE FINCA DE ARÁNDANOS
// Extraídos del catálogo 2026
// ═══════════════════════════════════════════

export const PRODUCTS: Product[] = [
  // ── MERMELADAS ──────────────────────────
  {
    id: 'mermelada-arandano',
    slug: 'mermelada-arandano',
    name: 'Mermelada de Arándano',
    shortDescription: 'Artesanal con trozos de fruta entera. Sin conservantes ni colorantes.',
    description: 'Elaborada artesanalmente con arándanos frescos de estación. Cocida a fuego lento para preservar el sabor auténtico. Sin conservantes, sin colorantes y sin aditivos de ningún tipo. Cada frasco contiene trozos de fruta entera.',
    price: 7500,
    images: [
      { url: 'https://images.unsplash.com/photo-1597528380946-1f3e6a27e8ab?w=600&q=80', alt: 'Mermelada de Arándano Finca de Arándanos', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['bestseller', 'organic'],
    stock: 48,
    sku: 'MERM-ARAN-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.9,
    reviewCount: 127,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', 'Sin Gluten'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'mermelada-arandano-sin-azucar',
    slug: 'mermelada-arandano-sin-azucar',
    name: 'Mermelada de Arándano Sin Azúcar',
    shortDescription: 'Sin azúcar añadida. Para quienes cuidan su alimentación sin renunciar al sabor.',
    description: 'Nuestra línea Sin Azúcar está pensada para quienes cuidan su alimentación sin renunciar al sabor. Sin azúcar añadida, sin conservantes, sin colorantes y sin aditivos. Comer natural siempre es la mejor elección.',
    price: 7500,
    images: [
      { url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&q=80', alt: 'Mermelada de Arándano Sin Azúcar', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['organic', 'new'],
    stock: 32,
    sku: 'MERM-ARAN-SA-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.8,
    reviewCount: 43,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', 'Sin Azúcar', 'Sin Gluten'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'mermelada-arandano-frambuesa',
    slug: 'mermelada-arandano-frambuesa',
    name: 'Mermelada Arándano con Frambuesa',
    shortDescription: 'La combinación perfecta de dos berries. Sabor intenso y natural.',
    description: 'La fusión perfecta de arándanos y frambuesas frescas de nuestra finca. Elaborada a fuego lento con fruta entera, preservando todos los aromas y sabores naturales.',
    price: 7500,
    images: [
      { url: 'https://images.unsplash.com/photo-1506802913710-d40caff4c9c6?w=600&q=80', alt: 'Mermelada Arándano con Frambuesa', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['bestseller'],
    stock: 28,
    sku: 'MERM-ARAN-FRAM-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.7,
    reviewCount: 89,
    isFeatured: false,
    isActive: true,
    certifications: ['GMO Free'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'mermelada-frambuesa',
    slug: 'mermelada-frambuesa',
    name: 'Mermelada de Frambuesa',
    shortDescription: 'Frambuesas frescas de temporada. Aroma intenso y color vibrante.',
    description: 'Mermelada de frambuesa elaborada con fruta seleccionada en su punto justo de madurez. Cocción artesanal que preserva el color, aroma e intensidad natural de la frambuesa.',
    price: 8000,
    compareAtPrice: 9500,
    images: [
      { url: 'https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=600&q=80', alt: 'Mermelada de Frambuesa', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['seasonal', 'new'],
    stock: 20,
    sku: 'MERM-FRAM-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.9,
    reviewCount: 56,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'mermelada-zarzamora',
    slug: 'mermelada-zarzamora',
    name: 'Mermelada de Zarzamora',
    shortDescription: 'Zarzamoras silvestres. Sabor profundo y color intenso.',
    description: 'Mermelada elaborada con zarzamoras cuidadosamente seleccionadas. Su sabor profundo y ligeramente ácido la convierte en la favorita para acompañar quesos y tostadas.',
    price: 7500,
    images: [
      { url: 'https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?w=600&q=80', alt: 'Mermelada de Zarzamora', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['organic'],
    stock: 35,
    sku: 'MERM-ZARZA-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.8,
    reviewCount: 74,
    isFeatured: false,
    isActive: true,
    certifications: ['GMO Free'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'mermelada-durazno',
    slug: 'mermelada-durazno',
    name: 'Mermelada de Durazno',
    shortDescription: 'Duraznos maduros de temporada. Dulce y aromática.',
    description: 'El clásico reinventado. Duraznos en su punto justo de madurez, cocidos lentamente para obtener una mermelada de color dorado con trozos de fruta y aroma inigualable.',
    price: 7500,
    images: [
      { url: 'https://images.unsplash.com/photo-1592502712628-c22d3af3e6ac?w=600&q=80', alt: 'Mermelada de Durazno', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['seasonal'],
    stock: 41,
    sku: 'MERM-DURAZ-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.6,
    reviewCount: 38,
    isFeatured: false,
    isActive: true,
    certifications: ['GMO Free'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'mermelada-limon',
    slug: 'mermelada-limon',
    name: 'Mermelada de Limón',
    shortDescription: 'Cítrica y fresca. Perfecta para desayunos y repostería.',
    description: 'Mermelada de limón artesanal con un equilibrio perfecto entre dulce y ácido. Ideal para acompañar scones, tostadas o para usar en recetas de repostería.',
    price: 7500,
    images: [
      { url: 'https://images.unsplash.com/photo-1587486937303-b9b47b2e79d6?w=600&q=80', alt: 'Mermelada de Limón', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['new'],
    stock: 25,
    sku: 'MERM-LIMON-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.7,
    reviewCount: 29,
    isFeatured: false,
    isActive: true,
    certifications: ['GMO Free'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'mermelada-frutos-rojos',
    slug: 'mermelada-frutos-rojos',
    name: 'Mermelada Frutos Rojos',
    shortDescription: 'Mix de berries de nuestra finca. Explosión de sabores naturales.',
    description: 'Una mezcla irresistible de arándanos, frambuesas, frutillas y zarzamoras frescas de nuestra finca. Rica en antioxidantes y con un sabor intenso y complejo.',
    price: 7500,
    images: [
      { url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', alt: 'Mermelada Frutos Rojos', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'jam',
    tags: ['bestseller', 'organic'],
    stock: 52,
    sku: 'MERM-FROJ-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.9,
    reviewCount: 103,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', 'Sin Gluten'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },

  // ── JUGOS ────────────────────────────────
  {
    id: 'jugo-arandano',
    slug: 'jugo-arandano',
    name: 'Jugo de Arándano',
    shortDescription: '100% natural. Sin conservantes. Rico en antioxidantes.',
    description: 'Jugo elaborado con arándanos frescos de nuestra propia finca. Sin conservantes, sin colorantes y sin aditivos. Cada botella captura el sabor auténtico de la fruta en su punto justo de madurez, preservando todos sus nutrientes y antioxidantes naturales.',
    price: 3000,
    images: [
      { url: 'https://images.unsplash.com/photo-1570197571499-166b36435e9f?w=600&q=80', alt: 'Jugo de Arándano', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'juice',
    tags: ['bestseller', 'organic'],
    stock: 60,
    sku: 'JUGO-ARAN-500',
    weight: 500,
    unit: '500 ml',
    rating: 4.8,
    reviewCount: 215,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', '100% Natural'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'jugo-arandano-sin-azucar',
    slug: 'jugo-arandano-sin-azucar',
    name: 'Jugo de Arándano Sin Azúcar',
    shortDescription: 'Todo el sabor natural, sin azúcar añadida. Ideal para deportistas.',
    description: 'La pureza del arándano sin ningún añadido. Sin azúcar, sin conservantes, sin colorantes. Todo el poder antioxidante del arándano en estado puro.',
    price: 3000,
    images: [
      { url: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=600&q=80', alt: 'Jugo de Arándano Sin Azúcar', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'juice',
    tags: ['organic', 'new'],
    stock: 44,
    sku: 'JUGO-ARAN-SA-500',
    weight: 500,
    unit: '500 ml',
    rating: 4.7,
    reviewCount: 88,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', 'Sin Azúcar', '100% Natural'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'jugo-frambuesa',
    slug: 'jugo-frambuesa',
    name: 'Jugo de Frambuesa',
    shortDescription: 'Frambuesas frescas exprimidas. Color vibrante y sabor intenso.',
    description: 'Jugo de frambuesa 100% natural elaborado con fruta fresca de temporada. Sin conservantes ni colorantes, preservando todos los nutrientes y el sabor inconfundible de la frambuesa.',
    price: 3500,
    compareAtPrice: 4200,
    images: [
      { url: 'https://images.unsplash.com/photo-1506966953602-2c4b98e4be2a?w=600&q=80', alt: 'Jugo de Frambuesa', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'juice',
    tags: ['seasonal', 'bestseller'],
    stock: 38,
    sku: 'JUGO-FRAM-500',
    weight: 500,
    unit: '500 ml',
    rating: 4.9,
    reviewCount: 67,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', '100% Natural'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'jugo-frutos-rojos',
    slug: 'jugo-frutos-rojos',
    name: 'Jugo Frutos Rojos',
    shortDescription: 'Mix de berries. Antioxidante natural. Sin conservantes.',
    description: 'Una explosión de frutos rojos en cada sorbo. Arándanos, frambuesas, zarzamoras y frutillas de nuestra finca en un jugo natural rico en vitaminas y antioxidantes.',
    price: 3000,
    images: [
      { url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&q=80', alt: 'Jugo Frutos Rojos', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'juice',
    tags: ['organic', 'bestseller'],
    stock: 50,
    sku: 'JUGO-FROJ-500',
    weight: 500,
    unit: '500 ml',
    rating: 4.8,
    reviewCount: 142,
    isFeatured: false,
    isActive: true,
    certifications: ['GMO Free', '100% Natural'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'jugo-ciruela',
    slug: 'jugo-ciruela',
    name: 'Jugo de Ciruela',
    shortDescription: 'Ciruelas maduras. Dulce natural y propiedades digestivas.',
    description: 'Jugo de ciruela artesanal con el dulzor natural de la fruta madura. Reconocido por sus propiedades digestivas y su rico sabor. Sin azúcar añadida ni conservantes.',
    price: 3000,
    images: [
      { url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&q=80', alt: 'Jugo de Ciruela', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'juice',
    tags: ['organic'],
    stock: 30,
    sku: 'JUGO-CIRUE-500',
    weight: 500,
    unit: '500 ml',
    rating: 4.6,
    reviewCount: 45,
    isFeatured: false,
    isActive: true,
    certifications: ['GMO Free', '100% Natural'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },

  // ── CONSERVAS ────────────────────────────
  {
    id: 'chutney-arandano',
    slug: 'chutney-arandano',
    name: 'Chutney de Arándano',
    shortDescription: 'Agridulce artesanal. Perfecto para quesos y carnes.',
    description: 'Nuestro chutney de arándano es una conserva artesanal de sabor agridulce, ideal para acompañar picadas, quesos maduros, carnes o simplemente disfrutar en cualquier momento. Elaborado con ingredientes seleccionados.',
    price: 6000,
    images: [
      { url: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=600&q=80', alt: 'Chutney de Arándano', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'organic',
    tags: ['new', 'organic'],
    stock: 22,
    sku: 'CHUT-ARAN-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.8,
    reviewCount: 31,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', 'Artesanal'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'pesto',
    slug: 'pesto',
    name: 'Pesto Artesanal',
    shortDescription: 'Albahaca fresca de la finca. Receta tradicional italiana.',
    description: 'Pesto elaborado con albahaca fresca cultivada en nuestra finca, aceite de oliva y los mejores ingredientes. Sin conservantes, con el sabor auténtico de una preparación casera.',
    price: 10000,
    compareAtPrice: 12000,
    images: [
      { url: 'https://images.unsplash.com/photo-1447078806655-40579c2520d6?w=600&q=80', alt: 'Pesto Artesanal', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'organic',
    tags: ['new', 'bestseller'],
    stock: 18,
    sku: 'PESTO-250',
    weight: 250,
    unit: '250 cc',
    rating: 4.9,
    reviewCount: 52,
    isFeatured: true,
    isActive: true,
    certifications: ['GMO Free', 'Artesanal'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'miel',
    slug: 'miel',
    name: 'Miel Natural',
    shortDescription: 'Miel pura de nuestra finca. Sin procesar. Directa del productor.',
    description: 'Miel 100% natural extraída en nuestra finca. Sin procesar, sin calentamiento excesivo, preservando todas sus propiedades naturales, enzimas y antioxidantes.',
    price: 5500,
    images: [
      { url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80', alt: 'Miel Natural', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'organic',
    tags: ['organic', 'bestseller'],
    stock: 30,
    sku: 'MIEL-360',
    weight: 360,
    unit: '360 cc',
    rating: 4.9,
    reviewCount: 78,
    isFeatured: false,
    isActive: true,
    certifications: ['100% Natural', 'Sin Procesar'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },

  // ── PACKS REGALO ─────────────────────────
  {
    id: 'pack-mermeladas-3',
    slug: 'pack-mermeladas-3',
    name: 'Pack 3 Mermeladas a Elección',
    shortDescription: 'Elige tus 3 sabores favoritos. El regalo perfecto.',
    description: 'Selecciona 3 mermeladas de nuestra colección completa. Presentadas en caja de regalo kraft artesanal. Ideal para regalar o para darte un capricho. Incluye tarjeta personalizada.',
    price: 21000,
    compareAtPrice: 24000,
    images: [
      { url: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?w=600&q=80', alt: 'Pack 3 Mermeladas', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'gift',
    tags: ['bestseller', 'new'],
    stock: 15,
    sku: 'PACK-MERM-3',
    weight: 1100,
    unit: '3 x 360cc',
    rating: 5.0,
    reviewCount: 34,
    isFeatured: true,
    isActive: true,
    certifications: ['Artesanal', 'Hecho a mano'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
  {
    id: 'cesta-gourmet',
    slug: 'cesta-gourmet',
    name: 'Cesta Gourmet Completa',
    shortDescription: 'Mermelada + Jugo + Conserva. La cesta campesina definitiva.',
    description: 'Nuestra cesta gourmet incluye una selección curada de nuestros mejores productos: 2 mermeladas, 2 jugos y 1 conserva artesanal. Presentada en cesta de mimbre con papel kraft y lazo. El regalo premium perfecto.',
    price: 38000,
    compareAtPrice: 45000,
    images: [
      { url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80', alt: 'Cesta Gourmet', isPrimary: true, width: 600, height: 600 }
    ],
    category: 'basket',
    tags: ['bestseller', 'seasonal'],
    stock: 8,
    sku: 'CESTA-GOURMET',
    weight: 3500,
    unit: '5 productos',
    rating: 5.0,
    reviewCount: 19,
    isFeatured: true,
    isActive: true,
    certifications: ['Artesanal', 'Hecho a mano'],
    origin: 'Finca propia, Argentina',
    createdAt: '2024-01-01',
    updatedAt: '2024-06-01',
  },
]

// ═══════════════════════════════════════════
// CATEGORÍAS
// ═══════════════════════════════════════════
export const CATEGORIES: Category[] = [
  {
    id: 'jam',
    name: 'Mermeladas',
    description: 'Artesanales con fruta fresca de estación. Sin conservantes ni colorantes.',
    image: 'https://images.unsplash.com/photo-1597528380946-1f3e6a27e8ab?w=800&q=80',
    slug: 'mermeladas',
    productCount: 12,
    featured: true,
  },
  {
    id: 'juice',
    name: 'Jugos Naturales',
    description: '100% naturales. Elaborados con fruta fresca de nuestra propia finca.',
    image: 'https://images.unsplash.com/photo-1570197571499-166b36435e9f?w=800&q=80',
    slug: 'jugos',
    productCount: 6,
    featured: true,
  },
  {
    id: 'organic',
    name: 'Conservas',
    description: 'Chutneys, pestos y conservas artesanales con ingredientes seleccionados.',
    image: 'https://images.unsplash.com/photo-1609501676725-7186f017a4b7?w=800&q=80',
    slug: 'conservas',
    productCount: 10,
    featured: true,
  },
  {
    id: 'gift',
    name: 'Packs Regalo',
    description: 'El regalo perfecto directo desde nuestra finca. Presentación artesanal.',
    image: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?w=800&q=80',
    slug: 'packs-regalo',
    productCount: 5,
    featured: true,
  },
  {
    id: 'basket',
    name: 'Cestas Gourmet',
    description: 'Cestas campesinas curadas con lo mejor de la finca. Para regalar o disfrutar.',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80',
    slug: 'cestas',
    productCount: 3,
    featured: true,
  },
  {
    id: 'seasonal',
    name: 'Temporada',
    description: 'Productos exclusivos de temporada. Disponibles por tiempo limitado.',
    image: 'https://images.unsplash.com/photo-1506802913710-d40caff4c9c6?w=800&q=80',
    slug: 'temporada',
    productCount: 4,
    featured: true,
  },
]

// ═══════════════════════════════════════════
// HELPERS
// ═══════════════════════════════════════════
export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug)
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter(p => p.category === category && p.isActive)
}

export function getFeaturedProducts(): Product[] {
  return PRODUCTS.filter(p => p.isFeatured && p.isActive)
}

export function formatARS(amount: number): string {
  return new Intl.NumberFormat('es-AR', {
    style: 'currency',
    currency: 'ARS',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}
